/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model

import ai.radius.blink.model.BulkErrorErrorsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errors 
 */


data class BulkError (

    @Json(name = "errors")
    val errors: kotlin.collections.List<BulkErrorErrorsInner>

) {


}

