/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param externalId 
 * @param error 
 */


data class BulkErrorErrorsInner (

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

