/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model

import ai.radius.blink.model.ScannedItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param deviceId 
 * @param status 
 * @param scanData 
 */


public data class ScanResponseData (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    @Json(name = "device_id")
    val deviceId: kotlin.String,

    @Json(name = "status")
    val status: ScanResponseData.Status,

    @Json(name = "scan_data")
    val scanData: kotlin.collections.List<ScannedItem>

) {

    /**
     * 
     *
     * Values: ACTIVE,IDLE
     */
    @JsonClass(generateAdapter = false)
    public enum class Status(public val value: kotlin.String) {
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "IDLE") IDLE("IDLE");
    }

}

