/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model

import ai.radius.blink.model.ScannedItemExtras

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lineItemId 
 * @param `data` 
 * @param dataEncoding 
 * @param extras 
 */


data class ScannedItem (

    @Json(name = "line_item_id")
    val lineItemId: kotlin.Int? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null,

    @Json(name = "data_encoding")
    val dataEncoding: ScannedItem.DataEncoding? = null,

    @Json(name = "extras")
    val extras: ScannedItemExtras? = null

) {

    /**
     * 
     *
     * Values: UPCMinusA,EANMinus13,GS1Minus128
     */
    @JsonClass(generateAdapter = false)
    enum class DataEncoding(val value: kotlin.String) {
        @Json(name = "UPC-A") UPCMinusA("UPC-A"),
        @Json(name = "EAN-13") EANMinus13("EAN-13"),
        @Json(name = "GS1-128") GS1Minus128("GS1-128");
    }

}

