/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Internal transaction ID
 * @param externalId External transaction ID
 */


data class TransactionDeleteRequest (

    /* Internal transaction ID */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* External transaction ID */
    @Json(name = "externalId")
    val externalId: kotlin.String? = null

) {


}

