/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model

import ai.radius.blink.model.TransactionCreateRequestItemsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param externalId 
 * @param deviceId 
 * @param storeTimezone 
 * @param transactionStartTime 
 * @param transactionEndTime 
 * @param items 
 */


data class TransactionCreateRequest (

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "device_id")
    val deviceId: kotlin.String? = null,

    @Json(name = "store_timezone")
    val storeTimezone: kotlin.String? = null,

    @Json(name = "transaction_start_time")
    val transactionStartTime: kotlinx.datetime.Instant? = null,

    @Json(name = "transaction_end_time")
    val transactionEndTime: kotlinx.datetime.Instant? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<TransactionCreateRequestItemsInner>? = null

) {


}

