/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.radius.blink.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sku 
 * @param upc 
 * @param quantity 
 */


data class TransactionCreateRequestItemsInner (

    @Json(name = "sku")
    val sku: kotlin.String,

    @Json(name = "upc")
    val upc: kotlin.String,

    @Json(name = "quantity")
    val quantity: kotlin.Int

) {


}

