/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model

import rai.blink.model.ScannedItemExtras

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lineItemId 
 * @param `data` 
 * @param extras 
 * @param dataEncoding 
 */
@Serializable

public data class ScannedItem (

    @SerialName(value = "line_item_id") @Required val lineItemId: kotlin.Int,

    @SerialName(value = "data") @Required val `data`: kotlin.String,

    @SerialName(value = "extras") @Required val extras: ScannedItemExtras,

    @SerialName(value = "data_encoding") val dataEncoding: ScannedItem.DataEncoding? = null

) {

    /**
     * 
     *
     * Values: UPCMinusA,EANMinus13,GS1Minus128
     */
    @Serializable
    public enum class DataEncoding(public val value: kotlin.String) {
        @SerialName(value = "UPC-A") UPCMinusA("UPC-A"),
        @SerialName(value = "EAN-13") EANMinus13("EAN-13"),
        @SerialName(value = "GS1-128") GS1Minus128("GS1-128");
    }

}

