/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model

import rai.blink.model.ScannedItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param deviceId 
 * @param status 
 * @param scanData 
 */
@Serializable

public data class ScanResponseData (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "device_id") @Required val deviceId: kotlin.String,

    @SerialName(value = "status") @Required val status: ScanResponseData.Status,

    @SerialName(value = "scan_data") @Required val scanData: kotlin.collections.List<ScannedItem>

) {

    /**
     * 
     *
     * Values: ACTIVE,IDLE
     */
    @Serializable
    public enum class Status(public val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "IDLE") IDLE("IDLE");
    }

}

