/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sku 
 * @param upc 
 * @param quantity 
 */
@Serializable

public data class TransactionCreateRequestItemsInner (

    @SerialName(value = "sku") @Required val sku: kotlin.String,

    @SerialName(value = "upc") @Required val upc: kotlin.String,

    @SerialName(value = "quantity") @Required val quantity: kotlin.Int

) {


}

