/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model

import rai.blink.model.TransactionCreateRequestItemsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param externalId 
 * @param deviceId 
 * @param storeTimezone 
 * @param transactionEndTime 
 * @param items 
 * @param transactionStartTime 
 */
@Serializable

public data class Transaction (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "externalId") @Required val externalId: kotlin.String,

    @SerialName(value = "device_id") @Required val deviceId: kotlin.String,

    @SerialName(value = "store_timezone") @Required val storeTimezone: kotlin.String,

    @SerialName(value = "transaction_end_time") @Required val transactionEndTime: kotlinx.datetime.Instant?,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<TransactionCreateRequestItemsInner>,

    @SerialName(value = "transaction_start_time") val transactionStartTime: kotlinx.datetime.Instant? = null

) {


}

