/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model

import rai.blink.model.BulkErrorErrorsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param errors 
 */
@Serializable

public data class BulkError (

    @SerialName(value = "errors") @Required val errors: kotlin.collections.List<BulkErrorErrorsInner>

) {


}

