/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param externalId 
 * @param error 
 */
@Serializable

public data class BulkErrorErrorsInner (

    @SerialName(value = "externalId") @Required val externalId: kotlin.String,

    @SerialName(value = "error") @Required val error: kotlin.String

) {


}

