/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package rai.blink.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param externalId 
 * @param sku 
 * @param upc 
 * @param name 
 * @param description 
 * @param upcEncoding 
 * @param icon 
 */
@Serializable

public data class Item (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "externalId") @Required val externalId: kotlin.String,

    @SerialName(value = "sku") @Required val sku: kotlin.String,

    @SerialName(value = "upc") @Required val upc: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "upc_encoding") val upcEncoding: kotlin.String? = null,

    @SerialName(value = "icon") val icon: kotlin.String? = null

) {


}

